
name: Create and publish Docker images

on:
  push:
    branches: ['master']

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: rust-cli-apt
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bionic Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bionic-x86_64/Dockerfile
          push: true
          tags: '${{ github.repository }}:bionic-x86_64'
