
name: Create and publish Docker images

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push bionic Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bionic-x86_64/Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:bionic-x86_64'
      - name: Build and push focal Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: focal-x86_64/Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:focal-x86_64'
      - name: Build and push stretch Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: stretch-x86_64/Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:stretch-x86_64'
      - name: Build and push buster Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: buster-x86_64/Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:buster-x86_64'
      - name: Build and push bullseye Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bullseye-x86_64/Dockerfile
          push: true
          tags: 'ghcr.io/${{ github.repository }}:bullseye-x86_64'
